version: '3.9'
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=${USERNAME}
      - RABBITMQ_DEFAULT_PASS=${PASSWORD}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_logs:/var/log/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      retries: 10

  app:
    platform: linux/amd64
    build:
      context: .
    environment:
      - NXF_HOME=/root/.nextflow
    env_file:
      - .env
    command: celery -A worker.celery_app worker --loglevel=info --concurrency=1
    volumes:
      - .:/app
    depends_on:
      rabbitmq:
        condition: service_healthy

  flower:
    build:
      context: .
    env_file:
      - .env
    environment:
      - NXF_HOME=/root/.nextflow
    command: celery -A worker.celery_app flower --port=5555
    ports:
      - 5556:5555
    volumes:
      - .:/app
    depends_on:
      - app

  db:
    image: postgres:15
    restart: always
    ports:
      - "5434:5432"
    expose:
      - "5434"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data_queue:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    env_file:
      - .env
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - app

volumes:
  rabbitmq_data:
  rabbitmq_logs:
  nextflow_cache:
  postgres_data_queue:
